title = "Gaurav Vaidya's website"
baseURL = "https://www.ggvaidya.com/"

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = false

markup.highlight.noClasses = false
theme = 'docura'
